config/routes.rb
Wikislam::Application.routes.draw do
  themes_for_rails

  resources :categories

  
  resources :articles do
    collection do
      get :list, :resources
    end
    member do
      get :show_article
    end
  end

  resources :rss_sources do
    collection do
      get :run
    end
  end

   root :to => 'articles#list'

end

app/models/rss_source.rb
class RssSource < ActiveRecord::Base
  attr_accessible :name, :status, :tag, :trusted, :url, :last_scrape
  has_many :articles

  def count_article
    
  end

end

app/controllers/rss_sources_controller.rb
require 'crawler'
class RssSourcesController < ApplicationController
  # GET /rss_sources
  # GET /rss_sources.json
  def index
    @rss_sources = RssSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rss_sources }
    end
  end



  # GET /rss_sources/1
  # GET /rss_sources/1.json
  def show
    @rss_source = RssSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rss_source }
    end
  end

  # GET /rss_sources/new
  # GET /rss_sources/new.json
  def new
    @rss_source = RssSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rss_source }
    end
  end

  # GET /rss_sources/1/edit
  def edit
    @rss_source = RssSource.find(params[:id])
  end

  # POST /rss_sources
  # POST /rss_sources.json
  def create
    @rss_source = RssSource.new(params[:rss_source])

    respond_to do |format|
      if @rss_source.save
        format.html { redirect_to @rss_source, notice: 'Rss source was successfully created.' }
        format.json { render json: @rss_source, status: :created, location: @rss_source }
      else
        format.html { render action: "new" }
        format.json { render json: @rss_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rss_sources/1
  # PUT /rss_sources/1.json
  def update
    @rss_source = RssSource.find(params[:id])

    respond_to do |format|
      if @rss_source.update_attributes(params[:rss_source])
        format.html { redirect_to @rss_source, notice: 'Rss source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rss_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_sources/1
  # DELETE /rss_sources/1.json
  def destroy
    @rss_source = RssSource.find(params[:id])
    @rss_source.destroy

    respond_to do |format|
      format.html { redirect_to rss_sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rss_sources_helper.rb
module RssSourcesHelper
end

app/views/rss_sources/_form.html.erb
<%= form_for(@rss_source) do |f| %>
  <% if @rss_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_source.errors.count, "error") %> prohibited this rss_source from being saved:</h2>

      <ul>
      <% @rss_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :trusted %><br />
    <%= f.number_field :trusted %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rss_sources/edit.html.erb
<h1>Editing rss_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @rss_source %> |
<%= link_to 'Back', rss_sources_path %>

app/views/rss_sources/index.html.erb
<h1>Listing rss_sources</h1>

<table class="table striped border">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Trusted</th>
    <th>Tag</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rss_sources.each do |rss_source| %>
  <tr>
    <td><%= rss_source.name %></td>
    <td><%= rss_source.url %></td>
    <td><%= rss_source.trusted %></td>
    <td><%= rss_source.tag %></td>
      <td><%= rss_source.status %></td>
      <td><%= link_to 'Show', rss_source, class: 'btn btn-mini' %>
          <%= link_to 'Edit', edit_rss_source_path(rss_source), class: 'btn btn-mini' %>
    <%= link_to 'Destroy', rss_source, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rss source', new_rss_source_path %>

app/views/rss_sources/new.html.erb
<h1>New rss_source</h1>

<%= render 'form' %>

<%= link_to 'Back', rss_sources_path %>

app/views/rss_sources/run.html.erb
run

app/views/rss_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rss_source.name %>
</p>

<p>
  <b>Url:</b>
  <%= @rss_source.url %>
</p>

<p>
  <b>Trusted:</b>
  <%= @rss_source.trusted %>
</p>

<p>
  <b>Tag:</b>
  <%= @rss_source.tag %>
</p>

<p>
  <b>Status:</b>
  <%= @rss_source.status %>
</p>


<%= link_to 'Edit', edit_rss_source_path(@rss_source) %> |
<%= link_to 'Back', rss_sources_path %>