config/routes.rb
Wikislam::Application.routes.draw do
  themes_for_rails

  resources :categories

  
  resources :articles do
    collection do
      get :list, :resources
    end
    member do
      get :show_article
    end
  end

  resources :rss_sources do
    collection do
      get :run
    end
  end

   root :to => 'articles#list'

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  
  attr_accessible :counter,:content, :shorturl,:image_url, :order, :rss_source_id, :site_url, :status, :summary, :title
  belongs_to :rss_source
  validates :title, uniqueness: true



  friendly_id :title, use: :slugged
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  theme 'mobile'
  def index
    #    @articles = Article.order("published asc")
    #
    #    respond_to do |format|
    #      format.html # index.html.erb
    #      format.json { render json: @articles }
    #    end
  end

  def list
    if params[:keyword].blank?
      if params[:rss_source_id].blank?
        @articles = Article.order("published desc").page(params[:page]).per(20)
      else
        @articles = Article.where(rss_source_id: params[:rss_source_id]).order("published desc").page(params[:page]).per(20)
      end
    else
      @articles = Article.where("title like ? or content like ?","%#{params[:keyword]}%","%#{params[:keyword]}%").order("published desc").page(params[:page]).per(20)
    end
  end


  def resources
    @rsssources = RssSource.where(status: 1)
  end

  def show_article
    @article = Article.find_by_slug(params[:id])
    self.count(params[:id])
  end

  def count(id)
    article = Article.find_by_slug(id)
    if article.nil?
      article.counter = 1
      article.save
    else
      article.counter = article.counter.to_i + 1
      article.save
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find_by_slug(params[:id])
    self.count(params[:id])
    render "show_article"
  end
  #
  #  # GET /articles/new
  #  # GET /articles/new.json
  #  def new
  #    @article = Article.new
  #
  #    respond_to do |format|
  #      format.html # new.html.erb
  #      format.json { render json: @article }
  #    end
  #  end
  #
  #  # GET /articles/1/edit
  #  def edit
  #    @article = Article.find(params[:id])
  #  end
  #
  #  # POST /articles
  #  # POST /articles.json
  #  def create
  #    @article = Article.new(params[:article])
  #
  #    respond_to do |format|
  #      if @article.save
  #        format.html { redirect_to @article, notice: 'Article was successfully created.' }
  #        format.json { render json: @article, status: :created, location: @article }
  #      else
  #        format.html { render action: "new" }
  #        format.json { render json: @article.errors, status: :unprocessable_entity }
  #      end
  #    end
  #  end
  #
  #  # PUT /articles/1
  #  # PUT /articles/1.json
  #  def update
  #    @article = Article.find(params[:id])
  #
  #    respond_to do |format|
  #      if @article.update_attributes(params[:article])
  #        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
  #        format.json { head :no_content }
  #      else
  #        format.html { render action: "edit" }
  #        format.json { render json: @article.errors, status: :unprocessable_entity }
  #      end
  #    end
  #  end
  #
  #  # DELETE /articles/1
  #  # DELETE /articles/1.json
  #  def destroy
  #    @article = Article.find(params[:id])
  #    @article.destroy
  #
  #    respond_to do |format|
  #      format.html { redirect_to articles_url }
  #      format.json { head :no_content }
  #    end
  #  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br />
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :rss_source_id %><br />
    <%= f.number_field :rss_source_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_list.html.erb
<div class="col-lg-3 article">
  <div class="panel panel-default">
    <div class="panel-heading"><%= raw truncate(article.title,length: 32, omission: '...')%></div>
    <div class="panel-body" style="padding: 2px">
      <p>
        <%= image_tag(article.image_url,style: 'width: 120px; height: 150px;float: left;margin: 10px') if not article.image_url.nil?  %>
        <%#= ActionView::Base.full_sanitizer.sanitize(truncate(article.content.strip, length: 100, omission: '..read more')).html_safe %>
        <%- temp = ActionView::Base.full_sanitizer.sanitize(article.content).html_safe%>
        <%= truncate(temp.delete!("&#13;"),length: 150) %>  
        <%= link_to "READ MORE", show_article_article_path(article.id), class: 'btn btn-danger btn-lg btn-small' %>
        </p>
      </div>
      <div class="panel-heading">
        
        <i class="icon-search"><%= link_to article.rss_source.name, article.site_url, target: '_blank'  %></i> |
        <i class="icon-search"><%= time_ago_in_words article.published %></i>
      </div>
    </div>

  </div>

app/views/articles/_list_article.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_list_article.html" %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Summary</th>
    <th>Image url</th>
    <th>Site url</th>
    <th>Rss source</th>
    <th>Status</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= article.summary %></td>
    <td><%= article.image_url %></td>
    <td><%= article.site_url %></td>
    <td><%= article.rss_source_id %></td>
    <td><%= article.status %></td>
    <td><%= article.order %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/list.html.erb
<div class="row-fluid">
  <div id="articles" class="span12" style="float: left">
    <%- @articles.each do |article|%>
      <%= render "list", article: article %>
    <%- end %>
  </div>
</div>
<div class="page">
<%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2>
  <%= @article.title %>
</h2>

<p>
  <b>Content:</b>
  <%=raw @article.content %>
</p>

<p>
  <b>Summary:</b>
  <%= @article.summary %>
</p>

<p>
  <b>Image url:</b>
  <%= @article.image_url %>
</p>

<p>
  <b>Site url:</b>
  <%= @article.site_url %>
</p>

<p>
  <b>Rss source:</b>
  <%= @article.rss_source_id %>
</p>

<p>
  <b>Status:</b>
  <%= @article.status %>
</p>

<p>
  <b>Order:</b>
  <%= @article.order %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/show_article.html.erb
<h2>
  <%= @article.title %>
</h2>

<p>
  <b>Content:</b>
  <%=raw @article.content %>
</p>

<p>
  <b>Summary:</b>
  <%= @article.summary %>
</p>

<p>
  <b>Image url:</b>
  <%= @article.image_url %>
</p>

<p>
  <b>Site url:</b>
  <%= @article.site_url %>
</p>

<p>
  <b>Rss source:</b>
  <%= @article.rss_source_id %>
</p>

<p>
  <b>Status:</b>
  <%= @article.status %>
</p>

<p>
  <b>Order:</b>
  <%= @article.order %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>